on:
  push:
    branches:
      - main

name: Project

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main
    - name: Package
      run: |
        npm ci
        npm test
        npm run package
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git add .
